language: go
go_import_path: github.com/ondrejit/glok

go:
  - 1.7.x
  - master

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y

install:
  - glide install
  - go build

before_script:
  - go vet $(glide novendor)

script:
  - go test $(glide novendor)
